import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
.use(initReactI18next) // تهيئة react-i18next
.use(LanguageDetector) // اكتشاف لغة المتصفح تلقائيًا
  .init({
    fallbackLng: 'en', // اللغة الافتراضية
    resources: {
      en: {
        translation: {
          shop: "Shop",
          par_shop: "There are a many products you can buy any things likes laptop and you will enjoy it",
price:"Price",
category_search:"Search by category",
Rate:"Rate",
brands:"Search by brands",
add_cart:"Add to cart",
    SAR:"SAR",
    EG:"EG",
    delivery:"Free Home Delivery",
    delivery_par:"No more for buy price for delivery in this product",
    return:"Return Price",
    return_par:"ou can return the price after 15 deys , Show Detiles",
users_review:"Review Users",
order:"Order Now",
shop_all:"Shop All Products",
Home_Nav:"Home",
About_Nav:"About",
Shop_Nav:"Shop",
Contact_Nav:"Contact",
tests:"What Customers Says ?",

contact_head:"contact US",
contact_par:"Ask about products or offers and categories , here you can contact us for anythings , Get in touch with for any information Now !",
first:"First Name",
last:"Last Name",
email:"email",
phone:"phone",
Massege:"Massege",
send:"Send Massege",
cart:"Cart",
cart_title:"Title",
cart_category:"Category",
cart_price:"Price",
cart_count:"Count",
action:"Action",
partner:"We're proud to partner for Our succes",
partner_par:"Wew , we are partner with any Companies for succes the store !",
Top:"Top Products",
total_price:"Total",
subtotal:"Subtotal",
tax:"Tax",
discount:"Discount",
profile:"Profile",
public:"Public",
payment:"Payment",
submit:"submit",

wishlist:"Wishlist",
our:"Our Products",
all_products:"All Products",
products:"Product",
explore:"Explore Now",
categories_sec:"Browse The Categories",
categories_sec_par:"Browse your products easiley from Categories it's so easy !",

personal:"Personal Info",
userName:"UserName",
password:"Password",
address:"Address",
country:"Country",
city:"City",
postal_code:"Postal Code",
edit:"Edit",
cancel:"Cancel",
add:"Add",
card:"Your Card",
expire:"Expire Date",
card_num:"Card_Number",
add_payment:"Add Payment",
darkMode:"DarkMode",
lan:"Language",
price_kind:"Currency",
congrests:"Woooah , you are complete your account 🥳",
diffrent_payment:"Add A diffrent payment method ",
Next:"Next Step",
choose_payment:"Choose your saved payment",
finish:"Finish",
previsous:"Previous",
save1:"Save My Payment Methoud",
save2:"Save My Address",
order_coming:"your Order is Coming!",
total_price_tax:"Total Price (With Tax 20%)",
order_name:"Order Name",
order_par:"Your Order is after Ready To Go to Your Location , usually Take it 2 - 5 days",
recommend:"Recommend Products",
review:"Add Review",

}
      },
      ar: {
        translation: {
            shop: "المتجــر",
            par_shop: "هناك العديد من المنتجات التي يمكنك شراء أي شيء مثل الكمبيوتر المحمول وسوف تستمتع به",
  price:"السعــر",
  category_search:"البحث بالفئات",
  Rate:"التقييمات",
  brands:"البحث حسب الماركة",
  add_cart:"أضف للعربة",
SAR:"ر.س",
 EG:"ج.م",
 delivery:"التوصيل مجانا",
 delivery_par:"ليس هناك اي رسوم للتوصيل , رسوم التوصيل ببلاش ",
 return:"استرجاع المبلغ",
 return_par:"يمكنك إرجاع السعر بعد 15 يومًا، اعرف التفاصيل",
 users_review:"تقييمات المستخدمين",
order:"اطلب الأن",
review:"اضف تقييم",

Home_Nav:"المنزل",
About_Nav:"من نحن",
Shop_Nav:"المتجر",
Contact_Nav:"تواصل معنا",

contact_head:"تواصل معنا",
contact_par:"اسأل عن المنتجات أو العروض والفئات، هنا يمكنك الاتصال بنا لأي شيء، تواصل معنا للحصول على أي معلومات الآن!",
first:"الأسم الأول",
last:"الأسم الأخير",
email:"البريد الالكتروني",
phone:"الهاتف",
Massege:"الرسالة",
send:"ارسل الرسالة",
cart:"العربة",
cart_title:"اسم المنتج",
cart_category:"فئة المنتج",
cart_price:"السعر",
cart_count:"الكمية",
action:"الحدث",
wishlist:"المفضلة",
our:"منتجاتنا",
all_products:"جميع المنتجات",
products:"منتج",
explore:"تصفح المنتجات",
categories_sec:"تصفح فئات المنتجات",
categories_sec_par:"تصفح منتجاتك بسهولة من الفئات، إنه سهل للغاية!",

partner:"نحن فخورون  بالشراكة من اجل نجاحنا نجاحنا",
partner_par:"نحن شركاء مع أي شركة لتحقيق نجاح المتجر!",
Top:"المنتجات الرائجة",
tests:"تقييمات العملاء",
total_price:"اجمالي المبلغ",
subtotal:"المبلغ الاساسي",
tax:"الضريبة",
discount:"الخصم",

profile:"الملف الشخصي",
public:"العام",
payment:"المدفوعات",

personal:"المعلومات الشخصية",
userName:"الاسم الشخصي",
password:"كلمة المرور",
address:"العنوان",
country:"البلد",
city:"المدينة",
postal_code:"الرمز البريدي",
edit:"تعديل",
cancel:"إلغاء",
add:"إضافة",
submit:"إرسال",
card:"بطاقتك البنكية",
expire:"مدة الانتهاء",
card_num:"رقم البطاقة",
add_payment:"أضف وسيلة دفع",
darkMode:"الوضع الداكن",
lan:"اللغة",
price_kind:"نوع العملة",
congrests:"مذهل ! , لقد اكملت ملفك الشخصي بنجاح 🥳",
diffrent_payment:"اضف وسيلة دفع مختلفة",
Next:"التالي",
choose_payment:"اختر وسيلة الدفع المحفوظة,",
finish:"انتهاء",
previsous:"السابق",
save1:"احفظ وسيلة الدفع",
save2:"احفظ عنواني",
order_coming:"طلبك قيد التجهيز للوصول لك !",
total_price_tax:"اجمال المبلغ (مع ضريبة 20%)",
order_name:"اسم الطلب",
recommend:"منتجات قد تعجبك",
order_par:"طلبك رقم يتم تجهيزه الان للوصول لموقع المكتوب , عادة ما يستغرق هذا من يومين الى 5 ايام",
shop_all:"تصفح جميع المنتجات",
}
      }
    }
  });

export default i18n;
